const DATE_DEBOUNCE_MS = 500;
const DEFAULT_PAGE_SIZE = 20;
const EXPORT_PAGE_SIZE = 5000;
const ROLES_DROPDOWN_PAGE_SIZE = 100;
const SEARCH_DEBOUNCE_MS = 300;
const TENANTS_DROPDOWN_PAGE_SIZE = 200;

export {
  DATE_DEBOUNCE_MS,
  DEFAULT_PAGE_SIZE,
  EXPORT_PAGE_SIZE,
  ROLES_DROPDOWN_PAGE_SIZE,
  SEARCH_DEBOUNCE_MS,
  TENANTS_DROPDOWN_PAGE_SIZE,
};
