const DATE_DEBOUNCE_MS = 500;
const DEFAULT_PAGE_SIZE = 20;
const EXPORT_PAGE_SIZE = 5000;
const SEARCH_DEBOUNCE_MS = 300;

export { DATE_DEBOUNCE_MS, DEFAULT_PAGE_SIZE, EXPORT_PAGE_SIZE, SEARCH_DEBOUNCE_MS };
